// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnsoARaUwJgfB_cBdPmvB8rv9s9ZatZcU',
    appId: '1:670524678619:web:0162ee5d2b95b0f15447fe',
    messagingSenderId: '670524678619',
    projectId: 'doitnow-2005',
    authDomain: 'doitnow-2005.firebaseapp.com',
    storageBucket: 'doitnow-2005.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDEpQhWXZ2xWrROqD9kruI-K8BfB9S28',
    appId: '1:670524678619:android:25b6c223da6882655447fe',
    messagingSenderId: '670524678619',
    projectId: 'doitnow-2005',
    storageBucket: 'doitnow-2005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1oz9yX1KCMPesKn2SoaSKTbjR2pX-uI',
    appId: '1:670524678619:ios:02682229ef2310325447fe',
    messagingSenderId: '670524678619',
    projectId: 'doitnow-2005',
    storageBucket: 'doitnow-2005.firebasestorage.app',
    iosBundleId: 'com.example.doitnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA1oz9yX1KCMPesKn2SoaSKTbjR2pX-uI',
    appId: '1:670524678619:ios:02682229ef2310325447fe',
    messagingSenderId: '670524678619',
    projectId: 'doitnow-2005',
    storageBucket: 'doitnow-2005.firebasestorage.app',
    iosBundleId: 'com.example.doitnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnsoARaUwJgfB_cBdPmvB8rv9s9ZatZcU',
    appId: '1:670524678619:web:720c401d4c0541aa5447fe',
    messagingSenderId: '670524678619',
    projectId: 'doitnow-2005',
    authDomain: 'doitnow-2005.firebaseapp.com',
    storageBucket: 'doitnow-2005.firebasestorage.app',
  );
}
